version: '3'
services:
  emby:
    image: emby/embyserver
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./emby_config:/config
      - ./medias:/data
    deploy:
      labels:
        - traefik.enable=true

        - traefik.http.routers.emby.rule=Host(`emby.host.com`)
        - traefik.http.routers.emby.entrypoints=http
        - traefik.http.routers.emby.middlewares=tls-redirectscheme

        - traefik.http.services.emby.loadbalancer.server.port=8096

        - traefik.http.routers.emby-secure.rule=Host(`emby.host.com`)
        - traefik.http.routers.emby-secure.tls=true
        - traefik.http.routers.emby-secure.entrypoints=https
        - traefik.http.routers.emby-secure.tls.certresolver=letsencrypt
    networks:
      - traefik_traefik_proxy

  filebrowser:
    image: filebrowser/filebrowser
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./medias/complete:/srv
      - ./filebrowser/database.db:/database.db
    deploy:
      labels:
        - traefik.enable=true

        - traefik.http.routers.filebrowser.rule=Host(`filebrowser.host.com`)
        - traefik.http.routers.filebrowser.entrypoints=http
        - traefik.http.routers.filebrowser.middlewares=tls-redirectscheme

        - traefik.http.services.filebrowser.loadbalancer.server.port=80

        - traefik.http.routers.filebrowser-secure.rule=Host(`filebrowser.host.com`)
        - traefik.http.routers.filebrowser-secure.tls=true
        - traefik.http.routers.filebrowser-secure.entrypoints=https
        - traefik.http.routers.filebrowser-secure.tls.certresolver=letsencrypt
    networks:
      - traefik_traefik_proxy

  transmission:
    image: ghcr.io/linuxserver/transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - TRANSMISSION_WEB_HOME=/transmission-web-control/
    volumes:
      - ./transmission/config:/config
      - ./transmission/watch:/watch
      - ./medias:/downloads
    deploy:
      labels:
        - traefik.enable=true

        - traefik.http.routers.transmission.rule=Host(`transmission.host.com`)
        - traefik.http.routers.transmission.entrypoints=http
        - traefik.http.routers.transmission.middlewares=tls-redirectscheme

        - traefik.http.services.transmission.loadbalancer.server.port=9091

        - traefik.http.routers.transmission-secure.rule=Host(`transmission.host.com`)
        - traefik.http.routers.transmission-secure.tls=true
        - traefik.http.routers.transmission-secure.entrypoints=https
    networks:
      - traefik_traefik_proxy

networks:
  traefik_traefik_proxy:
    external: true